### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by RastaJedi** [neogeodev/FusionConverter#1]
I see about 7 pads for capacitors on both boards, including the through-hole ones. I see from many pictures of your fusion that the through-hole is not populated. I still see three caps in the front, and two on the back, but the BOM has only two caps listed. I think the BOM is incomplete? Please advise =). Trying to make one for personal use.

**Comment by furrtek** [comment]
BOM and JTAG info updated, sorry for the wait :)

**Comment by RastaJedi** [comment]
No worries! Thanks so much for the update! Really appreciate it!
