### ISSUE TITLE
Compiling the CPLD Firmware

### ISSUE THREAD

**Issue by Retrofletch** [neogeodev/FusionConverter#2]
Hello
i have built two of these and they both act the same, i get only the normal blue screen and rarely i get a verry garbled Neo geo logo trying to show.

When i tried to compile the firmware in Quartus i got many errors in regards to timings as there is no SDC file, i tried to make my own and got rid of almost all the complaints but i was more or less just making guesses so im not sure i did it correctly.

basicly im not at all confident in my compiled firmware and i suspect that is the issue as i have double checked soldering.

Is there a more complete set of quartus files to work with? or even better a confirmed and known working file to program the cpld with?

Looks like original files were made in quartus 12, i was not able to find that so i was using quartus 13, maybe thats a problem?
have tested several mvs cartidges.

reset wire is soldered in.

not sure how to proceed, any help appreciated
thanks

**Comment by furrtek** [comment]
Hello,

The files are known to work, the timing warnings given by Quartus can be ignored as the clocks are well under the fmax.
Blue screen means the console wasn't able to read the program ROMs, which the CPLD doesn't mess with. Most certainly several bad contacts.

**Comment by Retrofletch** [comment]
Hmm yes, but if i plug in a AES cart it will boot and all contacts both on the fusionconverter and the mvs cartridges have been cleaned, not sure what else it could be besides the cpld =/
